######################################################################
# Automatically generated by qmake (2.01a) ?t apr 26 23:27:16 2012
######################################################################

TEMPLATE = app
TARGET = kalkulacka
DEPENDPATH += ../ .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h matlib.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp matlib.cpp
