######################################################################
# Automatically generated by qmake (2.01a) ?t apr 26 23:14:10 2012
######################################################################

TEMPLATE = app
TARGET = kalkulacka
DEPENDPATH += ../../kalkulacka .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h matlib.h
FORMS += mainwindow.ui
SOURCES += ../test.c main.cpp mainwindow.cpp matlib.cpp
